{% set name = "ibm_db_django" %}
{% set version = "1.5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 091877861573e3e3d4af7bad0d4d4b1d9cb80201eae63351e8cafc91f289a162

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - django

test:
  imports:
    - ibm_db_django

about:
  home: https://pypi.org/project/ibm-db-django/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Django driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Django driver.
    The extension supports DB2 (LUW, zOS, i5)
  doc_url: https://github.com/ibmdb/python-ibmdb-django/blob/master/README.md
  dev_url: https://github.com/ibmdb/python-ibmdb-django
extra:
  recipe-maintainers:
    - amukherjee28
    - praveen-db2
